package services

import (
	"bytes"
	"fmt"
	"html/template"
	"net/smtp"
	"os"
	"strings"
)

// Mailer is the interface all mail backends implement.
type Mailer interface {
	SendInvoice(to, customerName, invoiceNumber string, amount float64, pdfURL string) error
	SendWelcome(to, name string) error
	SendPasswordReset(to, name, resetURL string) error
	SendContactMessage(to, fromName, fromEmail, subject, message string) error
}

// NoopMailer silently discards all mail (default when SMTP is unconfigured).
type NoopMailer struct{}

func (NoopMailer) SendInvoice(to, customerName, invoiceNumber string, amount float64, pdfURL string) error {
	return nil
}
func (NoopMailer) SendWelcome(to, name string) error                                     { return nil }
func (NoopMailer) SendPasswordReset(to, name, url string) error                          { return nil }
func (NoopMailer) SendContactMessage(to, fromName, fromEmail, subject, message string) error {
	return nil
}

// SMTPMailer sends real email via SMTP.
type SMTPMailer struct {
	host     string
	port     string
	username string
	password string
	from     string
}

// NewMailer returns an SMTPMailer if SMTP_HOST is set, otherwise NoopMailer.
func NewMailer() Mailer {
	host := os.Getenv("SMTP_HOST")
	if host == "" {
		return NoopMailer{}
	}
	port := os.Getenv("SMTP_PORT")
	if port == "" {
		port = "587"
	}
	from := os.Getenv("SMTP_FROM")
	if from == "" {
		from = "noreply@invobill.in"
	}
	return &SMTPMailer{
		host:     host,
		port:     port,
		username: os.Getenv("SMTP_USER"),
		password: os.Getenv("SMTP_PASS"),
		from:     from,
	}
}

func (m *SMTPMailer) send(to, subject, htmlBody string) error {
	auth := smtp.PlainAuth("", m.username, m.password, m.host)
	msg := []byte(strings.Join([]string{
		"MIME-Version: 1.0",
		"Content-Type: text/html; charset=UTF-8",
		"From: InvoBill <" + m.from + ">",
		"To: " + to,
		"Subject: " + subject,
		"",
		htmlBody,
	}, "\r\n"))
	return smtp.SendMail(m.host+":"+m.port, auth, m.from, []string{to}, msg)
}

func (m *SMTPMailer) SendInvoice(to, customerName, invoiceNumber string, amount float64, pdfURL string) error {
	const tpl = `<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;background:#f5f6fa;margin:0;padding:24px">
<div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)">
  <div style="background:linear-gradient(135deg,#4338ca,#6366f1);padding:28px 32px">
    <h1 style="color:#fff;margin:0;font-size:22px;font-weight:800">Invoice from InvoBill</h1>
  </div>
  <div style="padding:28px 32px">
    <p style="color:#374151;font-size:15px">Hi <strong>{{.CustomerName}}</strong>,</p>
    <p style="color:#6b7280;font-size:14px;line-height:1.7">
      Please find your invoice <strong>{{.InvoiceNumber}}</strong> for the amount of
      <strong style="color:#4f46e5">&#8377;{{.Amount}}</strong>.
    </p>
    {{if .PDFURL}}
    <a href="{{.PDFURL}}" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:16px 0">
      Download Invoice PDF
    </a>
    {{end}}
    <p style="color:#9ca3af;font-size:12px;margin-top:24px;border-top:1px solid #e5e7eb;padding-top:16px">
      This invoice was generated by InvoBill · <a href="https://invobill.in" style="color:#6366f1">invobill.in</a>
    </p>
  </div>
</div></body></html>`

	data := struct {
		CustomerName, InvoiceNumber, PDFURL string
		Amount                              string
	}{
		CustomerName:  customerName,
		InvoiceNumber: invoiceNumber,
		PDFURL:        pdfURL,
		Amount:        fmt.Sprintf("%.2f", amount),
	}
	var buf bytes.Buffer
	if err := template.Must(template.New("").Parse(tpl)).Execute(&buf, data); err != nil {
		return err
	}
	return m.send(to, "Invoice "+invoiceNumber+" from InvoBill", buf.String())
}

func (m *SMTPMailer) SendWelcome(to, name string) error {
	body := fmt.Sprintf(`<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;background:#f5f6fa;margin:0;padding:24px">
<div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)">
  <div style="background:linear-gradient(135deg,#4338ca,#6366f1);padding:28px 32px">
    <h1 style="color:#fff;margin:0;font-size:22px;font-weight:800">Welcome to InvoBill!</h1>
  </div>
  <div style="padding:28px 32px">
    <p style="color:#374151;font-size:15px">Hi <strong>%s</strong>,</p>
    <p style="color:#6b7280;font-size:14px;line-height:1.7">
      Your account is ready. Start creating GST-compliant invoices, managing inventory, and tracking payments — all from one place.
    </p>
    <a href="https://invobill.in/dashboard" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin:16px 0">
      Go to Dashboard
    </a>
    <p style="color:#9ca3af;font-size:12px;margin-top:24px;border-top:1px solid #e5e7eb;padding-top:16px">
      InvoBill · <a href="https://invobill.in" style="color:#6366f1">invobill.in</a>
    </p>
  </div>
</div></body></html>`, name)
	return m.send(to, "Welcome to InvoBill, "+name+"!", body)
}

func (m *SMTPMailer) SendPasswordReset(to, name, resetURL string) error {
	body := fmt.Sprintf(`<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;background:#f5f6fa;margin:0;padding:24px">
<div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#4338ca,#6366f1);padding:28px 32px">
    <h1 style="color:#fff;margin:0;font-size:22px;font-weight:800">Password Reset</h1>
  </div>
  <div style="padding:28px 32px">
    <p style="color:#374151">Hi %s, click below to reset your password. Link expires in 1 hour.</p>
    <a href="%s" style="display:inline-block;background:#4f46e5;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">
      Reset Password
    </a>
    <p style="color:#9ca3af;font-size:12px;margin-top:24px">If you didn't request this, ignore this email.</p>
  </div>
</div></body></html>`, name, resetURL)
	return m.send(to, "Reset your InvoBill password", body)
}

func (m *SMTPMailer) SendContactMessage(to, fromName, fromEmail, subject, message string) error {
	body := fmt.Sprintf(`<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;background:#f5f6fa;margin:0;padding:24px">
<div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)">
  <div style="background:linear-gradient(135deg,#4338ca,#6366f1);padding:24px 32px">
    <h2 style="color:#fff;margin:0;font-size:18px;font-weight:700">New Contact Message — InvoBill</h2>
  </div>
  <div style="padding:24px 32px">
    <table style="width:100%%;border-collapse:collapse;font-size:14px">
      <tr><td style="padding:8px 0;color:#6b7280;width:100px;font-weight:600">From</td><td style="padding:8px 0;color:#111827">%s</td></tr>
      <tr><td style="padding:8px 0;color:#6b7280;font-weight:600">Email</td><td style="padding:8px 0"><a href="mailto:%s" style="color:#4f46e5">%s</a></td></tr>
      <tr><td style="padding:8px 0;color:#6b7280;font-weight:600">Subject</td><td style="padding:8px 0;color:#111827">%s</td></tr>
    </table>
    <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin-top:12px">
      <p style="color:#374151;font-size:14px;line-height:1.7;margin:0;white-space:pre-wrap">%s</p>
    </div>
    <p style="color:#9ca3af;font-size:11px;margin-top:20px;border-top:1px solid #e5e7eb;padding-top:12px">
      Sent via invobill.in contact form
    </p>
  </div>
</div></body></html>`, fromName, fromEmail, fromEmail, subject, message)
	return m.send(to, "Contact: "+subject+" (from "+fromName+")", body)
}
